services:    
  nessus:
    container_name: nessus
    image: tenableofficial/nessus
    ports:
      - 8834:8834
    restart: always
    volumes:
      - nessusvolume:/opt/nessus
    networks:
      - nessus

volumes:
  nessusvolume:
    name: nessusvolume

networks:
  nessus:
    driver: bridge
    name: nessus
